baseURL = 'https://tashfeen.org/'
languageCode = 'en-GB'
title = 'tashfeen.org'
disableHugoGeneratorInject = true
enableRobotsTXT = true
copyright = '© Tashfeen 2025 — licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

[params]
  [params.author]
    name = 'Tashfeen'
    email = 'tashfeen@ou.edu'

[outputs]
  home = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
  [[menus.main]]
    name = 'Zoom'
    pageRef = '/posts/office-hours/'
    weight = 20
  [[menus.main]]
    name = 'Colophon'
    pageRef = '/colophon'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]